WM.Register/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WM.Register.DAO;
using WM.Register.MD5;
using WM.Register.Models;
using PagedList;

namespace WM.Register.Controllers
{
    public class RegisterController : Controller
    {
        [Authorize]
        // GET: Register
        public ActionResult Index(int? page)
        {
           
            if (page == null) page = 1;            
            var srv_VNOGateWay_Merchants = (from l in StoreProceduce.ListAllMerchant()
                                            select l).OrderBy(x => x.id);

            //var links = new DB().Database.SqlQuery<int>("select * from dbo.srv_VNOGateWay_Merchant").ToList();

            // 4. Tạo kích thước trang (pageSize) hay là số Link hiển thị trên 1 trang
            int pageSize = 3;

            // 4.1 Toán tử ?? trong C# mô tả nếu page khác null thì lấy giá trị page, còn
            // nếu page = null thì lấy giá trị 1 cho biến pageNumber.
            int pageNumber = (page ?? 1);
            var list = StoreProceduce.ListAllMerchant();       
            return View(list.ToPagedList(pageNumber, pageSize));
        }        
        [HttpGet]
        public ActionResult Register()
        {

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(HttpPostedFileBase file, srv_VNOGateWay_Merchant srv_VNOGateWay_Merchant)
        {
            if (ModelState.IsValid)
            {
                string filename = null;
                if (file == null)
                {
                    srv_VNOGateWay_Merchant.logo = "";
                    StoreProceduce.InsertMerchant(srv_VNOGateWay_Merchant);
                    return Json(new { srv_VNOGateWay_Merchant, JsonRequestBehavior.AllowGet });
                }
                else
                {                    
                    filename = file.FileName;
                    string filePathMerchant = Server.MapPath("~/Content/Uploads/Merchant");                    
                    string savedFileName = Path.Combine(filePathMerchant, filename);
                    file.SaveAs(savedFileName);
                    srv_VNOGateWay_Merchant.logo = filename;
                }
                StoreProceduce.InsertMerchant(srv_VNOGateWay_Merchant);
                return Json(new { srv_VNOGateWay_Merchant, JsonRequestBehavior.AllowGet }); 
            }           
            return Json(new { srv_VNOGateWay_Merchant, JsonRequestBehavior.AllowGet });
        }
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var getById=StoreProceduce.GetMerchantById(id);           
            if (getById == null)
            {
                return HttpNotFound();
            }
            return View(getById);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit(HttpPostedFileBase file, srv_VNOGateWay_Merchant srv_VNOGateWay_Merchant)
        {
            if (User.Identity.IsAuthenticated)
            {
                if (ModelState.IsValid)
                {                   
                    string filename = null;
                    if (file == null)
                    {                                               
                        srv_VNOGateWay_Merchant.updated_by = (User as WebIPrincipal).User.id;
                        StoreProceduce.UpdateMerchantWhenLogoNull(srv_VNOGateWay_Merchant);
                        return Json(new { srv_VNOGateWay_Merchant, JsonRequestBehavior.AllowGet });
                    }
                    else
                    {                        
                        filename = file.FileName;
                        string filePathMerchant = Server.MapPath("~/Content/Uploads/Merchant");                        
                        string savedFileName = Path.Combine(filePathMerchant, filename);
                        file.SaveAs(savedFileName);
                        //file.SaveAs(Server.MapPath("~/Content/Uploads/Merchant" + filename));
                        srv_VNOGateWay_Merchant.logo = filename;
                    }                   
                    srv_VNOGateWay_Merchant.updated_by = (User as WebIPrincipal).User.id;
                    StoreProceduce.UpdateMerchant(srv_VNOGateWay_Merchant);
                    return Json(new { srv_VNOGateWay_Merchant, JsonRequestBehavior.AllowGet });
                }
                var errors = ModelState.SelectMany(x => x.Value.Errors.Select(z => z.Exception));
            }
            else
            {
                return RedirectToAction("Login", "Login");
            }
            return Json(new { srv_VNOGateWay_Merchant, JsonRequestBehavior.AllowGet });
        }
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var getById = StoreProceduce.GetMerchantById(id);           
            if (getById == null)
            {
                return HttpNotFound();
            }
            return View(getById);
        }
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var getById = StoreProceduce.GetMerchantById(id); 
            if(getById == null)           
            {
                return HttpNotFound();
            }
            return View(getById);
        }
        [HttpPost]
        [Authorize]
        public ActionResult Delete(int? id, srv_VNOGateWay_Merchant srv_VNOGateWay_Merchant)
        {
            if (id != null)
            {
                var delete = new RegisterDbContext().Database.SqlQuery<srv_VNOGateWay_Merchant>("exec [dbo].[Deletesrv_VNOGateWay_Merchant_ById] @Id = " + id).FirstOrDefault();
            }
            else
            {
                return HttpNotFound();
            }
            return Json(srv_VNOGateWay_Merchant, JsonRequestBehavior.AllowGet);
        }

    }
}

WM.Register/Controllers/Transaction_MerchantController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WM.Register.DAO;
using WM.Register.Models;

namespace WM.Register.Controllers
{
    public class Transaction_MerchantController : Controller
    {
        // GET: Transaction_Merchant
        public ActionResult TransactionList(srv_VNOGateway_transactions srv_VNOGateway_transactions)
        {
            //var cookie = HttpContext.Current.Request.Cookies[FormsAuthentication.FormsCookieName];
            if (User.Identity.IsAuthenticated)
            {
                srv_VNOGateway_transactions.merchant_id = (User as WebIPrincipal).User.id;
                var list = StoreProceduce.ListTransactionByMerchantId(srv_VNOGateway_transactions);
                return View(list);
            }
            else
            {
                return RedirectToAction("Login","Login");
            }
            
        }
    }
}

WM.Register/Views/Shared/_Layout.cshtml
@{
    ViewBag.Title = "Home";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="keywords" content="au theme template">
    <!-- Fontfaces CSS-->
    <link href="~/Content/Home/css/font-face.css" rel="stylesheet" />
    <link href="~/Content/Home/vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/Home/vendor/font-awesome-5/css/fontawesome-all.min.css" rel="stylesheet" />
    <link href="~/Content/Home/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" />
    <!-- Bootstrap CSS-->
    <link href="~/Content/Home/vendor/bootstrap-4.1/bootstrap.min.css" rel="stylesheet" />
    <!-- Vendor CSS-->
    <link href="~/Content/Home/vendor/animsition/animsition.min.css" rel="stylesheet" />
    <link href="~/Content/Home/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet" />
    <link href="~/Content/Home/vendor/wow/animate.css" rel="stylesheet" />
    <link href="~/Content/Home/vendor/css-hamburgers/hamburgers.min.css" rel="stylesheet" />
    <link href="~/Content/Home/vendor/slick/slick.css" rel="stylesheet" />
    <link href="~/Content/Home/vendor/select2/select2.min.css" rel="stylesheet" />
    <link href="~/Content/Home/vendor/perfect-scrollbar/perfect-scrollbar.css" rel="stylesheet" />
    <!-- Main CSS-->
    <link href="~/Content/Home/css/theme.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="animsition">
    <div class="page-wrapper">
        <!-- HEADER MOBILE-->
        <header class="header-mobile d-block d-lg-none">
            <div class="header-mobile__bar">
                <div class="container-fluid">
                    <div class="header-mobile-inner">
                        <a class="logo" href="#">
                            @*<img src="~Content/Home/images/icon/logo.png" alt="CoolAdmin" />*@
                            <img src="~/Content/Home/images/WM_new_logo.png" style="height:80px;" />
                        </a>
                    </div>
                </div>
            </div>
        </header>
        <!-- END HEADER MOBILE-->
        <!-- MENU SIDEBAR-->
        <aside class="menu-sidebar d-none d-lg-block">
            <div class="logo">
                <a href="https://webmoney.com.vn/">
                    <img src="~/Content/Home/images/WM_new_logo.png" style="height:80px;" />
                </a>
            </div>
            <div class="menu-sidebar__content js-scrollbar1" style="border-right: solid 1px; border-color:whitesmoke">
                <nav class="navbar-sidebar">
                    <ul class="list-unstyled navbar__list">
                        <li>
                            <a href="@Url.Action("Index","Register")">
                                <i class="fas fa-chart-bar"></i>List Of Merchants
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("TransactionList","Transaction_Merchant")">
                                <i class="fas fa-chart-bar"></i>List Of Transactions
                            </a>
                        </li>

                    </ul>
                </nav>
            </div>
        </aside>
        <!-- END MENU SIDEBAR-->
        <!-- PAGE CONTAINER-->
        <div class="page-container">
            <!-- HEADER DESKTOP-->
            <header class="header-desktop">
                <div class="section__content section__content--p30">
                    <div class="container-fluid">
                        <div class="header-wrap">
                            <form class="form-header" action="" method="GET">
                               
                            </form>
                            <div class="account-wrap">
                                <div class="account-item clearfix js-item-menu">
                                    <div class="content">
                                        <a class="js-acc-btn" href="#">@((User as WebIPrincipal).User.merchant_name)</a>
                                    </div>
                                    <div class="account-dropdown js-dropdown">
                                        <div class="info clearfix">
                                            <div class="image">
                                                <a href="#">
                                                    <img src="~/Content/Uploads/Merchant/@((User as WM.Register.WebIPrincipal).User.logo) " />
                                                </a>
                                            </div>
                                            <div class="content">
                                                <h5 class="name">
                                                    <a href="#">@((User as WebIPrincipal).User.merchant_name)</a>
                                                </h5>
                                                <span class="email">@User.Identity.Name</span>
                                            </div>
                                        </div>
                                        <div class="account-dropdown__body">
                                            <div class="account-dropdown__item">
                                                <a href="@Url.Action("ChangePass","Login")">
                                                    <i class="zmdi zmdi-account"></i>Change Password
                                                </a>
                                            </div>
                                        </div>
                                        <div class="account-dropdown__footer">
                                            <a href="@Url.Action("Logout","Login")">
                                                <i class="zmdi zmdi-power"></i>Logout
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
        </div>
        <!-- HEADER DESKTOP-->
        <!-- MAIN CONTENT-->
        <div class="main-content">
            <div class="container body-content" style="padding-top:initial; margin-top:-100px;">
                @RenderBody()
                @*<footer>
                    <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
                </footer>*@
            </div>
        </div>
        <!-- END MAIN CONTENT-->
        <!-- END PAGE CONTAINER-->
    </div>
    <!-- Jquery JS-->
    <script src="~/Content/Home/vendor/jquery-3.2.1.min.js"></script>
    <!-- Bootstrap JS-->
    <script src="~/Content/Home/vendor/bootstrap-4.1/popper.min.js"></script>
    <script src="~/Content/Home/vendor/bootstrap-4.1/bootstrap.min.js"></script>
    <!-- Vendor JS       -->
    <script src="~/Content/Home/vendor/slick/slick.min.js"></script>
    <script src="~/Content/Home/vendor/wow/wow.min.js"></script>
    <script src="~/Content/Home/vendor/animsition/animsition.min.js"></script>
    <script src="~/Content/Home/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
    <script src="~/Content/Home/vendor/counter-up/jquery.waypoints.min.js"></script>
    <script src="~/Content/Home/vendor/counter-up/jquery.counterup.min.js"></script>
    <script src="~/Content/Home/vendor/circle-progress/circle-progress.min.js"></script>
    <script src="~/Content/Home/vendor/perfect-scrollbar/perfect-scrollbar.js"></script>
    <script src="~/Content/Home/vendor/chartjs/Chart.bundle.min.js"></script>
    <script src="~/Content/Home/vendor/select2/select2.min.js"></script>
    <!-- Main JS-->
    <script src="~/Content/Home/js/main.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WM.Register/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("WEBMONEY", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            @*<div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "HelpPage" }, null)</li>
                </ul>
            </div>*@
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        @*<footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>*@
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>